node.name: "es01"
cluster.name: todocluster
network.host: 0.0.0.0
cluster.routing.allocation.enable: all
xpack.security.enabled: false
node.roles: [ master, data, ingest ]
discovery.seed_hosts: [ "es02"]
cluster.initial_master_nodes:  [ "es01" ]
bootstrap.memory_lock: true
