# connect to mongoDB using the following URL
mongo-url ="mongodb://root:secret@mongodb:27017/testDB?authSource=admin"

# connect to elasticsearch using the following URL
elasticsearch-urls = [ "http://es01:9200" ]

# copy entire collections or views from MongoDB to Elasticsearch
# direct-read-namespaces = [ "testDB.todos" ]

# Listen for changes for entire database or entire deployment
change-stream-namespaces = [ "testDB.todos" ]

# use 4 go routines cocurrently pushing documents to Elasticsearch
elasticsearch-max-conns = 100

# resume processing from a timestamp saved in a previous run
resume = true

gzip = true
stats = false
index-stats = false
verbose = true

# do not exit after full-sync, rather continue tailing the changes
exit-after-direct-reads = true
# save logs into log
[logs]
error = "logs/error.log"

[[mapping]]
namespace = "testDB.todos"
index = "todos"

[[filter]]
namespace = "testDB.todos"
path="filter/base.js"

[[script]]
namespace = "testDB.todos"
path = "scripts/collect_todos.js"
routing = true

